---
- name: Add PostgreSQL GPG key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL APT repository
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_facts['distribution_release'] }}-pgdg main"
    state: present
    filename: pgdg

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install PostgreSQL 17
  package:
    name:
      - postgresql-17
      - postgresql-contrib-17
      - postgresql-client-17
    state: present

- name: Ensure PostgreSQL service is started and enabled
  ansible.builtin.systemd:
    name: postgresql
    state: started

- name: Install Python PostgreSQL adapter (psycopg2)
  ansible.builtin.apt:
    name: python3-psycopg2
    state: present
