# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE:
  - SPELL # Uncomment to disable checks of spelling mistakes
  # - COPYPASTE # Uncomment to disable checks of excessive copy-pastes

SHOW_ELAPSED_TIME: true

# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true

PYTHON_BANDIT_FILTER_REGEX_EXCLUDE: ^molecule?/

# config is created during megalinter ci run and king fisher complains about credential in there
REPOSITORY_KINGFISHER_ARGUMENTS: "--exclude .git/"

# ignore symlinked tasks/main.yml by prettier
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: '(^|/)(roles/(docker-compose|dyndns_client|k3s|linux_base|linux_bootstrap|linux_router|netplan|pihole)/tasks/main\.yml)$'
