---
- name: Converge
  hosts: all
  become: yes
  
  vars:
    pdns_records_manual:
      - name: www
        zone: example.local
        type: A
        content: 192.168.1.100
        ttl: 3600
  
  pre_tasks:
    - name: Install dig for testing
      apt:
        name: dnsutils
        state: present
        update_cache: yes
  
  roles:
    - role: powerdns
