---
- name: Install nftables
  package:
    name:
      - nftables
      - ufw
    state: present

- name: Enable and start nftables service
  systemd:
    name: nftables
    enabled: yes
    state: started

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes
