---
wireguard_interface: wg0

wireguard_internal_server_ip: "10.10.0.1/24"
wireguard_port: 51820

# Peers configuration
wireguard_client_peers: []
# Example:
# wireguard_peers:
#   - name: "alice"
#     ip: "10.10.0.2/32"

# DNS servers (optional)
wireguard_dns: []

# MTU (optional)
wireguard_mtu: ""

# PostUp and PostDown commands (optional)
wireguard_post_up: []
wireguard_post_down: []
