---
wireguard_company: "acme"
wireguard_port: 51820

# Peers configuration
wireguard_client_peers: []
# Example:
# wireguard_client_peers:
#   - name: "alice"
#     ip: "10.10.0.2/32"

# DNS servers (optional)
wireguard_dns_servers: [10.10.0.1]

# MTU (optional)
wireguard_mtu: ""

# PostUp and PostDown commands (optional)
wireguard_post_up: []
wireguard_post_down: []
