---
driver:
  name: docker
platforms:
  - name: instance
    image: localhost/ubuntu-test:24.04
    pre_build_image: true
provisioner:
  name: ansible
  options:
    v: true
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  inventory:
    hosts:
      all:
        hosts:
          instance:
            ansible_user: test-admin
            # admin password hash for 'test'
            infra_admin_password_hash: "$$6$$ro9AkmNC.NW/KyC9$$sGlcqEcnu4y2dQB179R0t6IREfrj3GWSCBRIhckdwPqWYZ1YU1wAhLQnRgaRhCZ8FIIxQh5TuoBvPHl/j4D/j0"
            timezone: "Europe/Zurich"
            skip_ipv6_disable: true
