- name: Ensure latest apt cache
  apt:
    update_cache: true
  when: ansible_os_family == "Debian"
- name: Ensure sudo is installed
  apt:
    name: sudo

- name: Make sure password for {{ ansible_user }} is set (console only login, no ssh)
  user:
    name: "{{ ansible_user }}"
    password: "{{ infra_admin_password_hash }}"

- name: Ensure /etc/update-motd.d/60-unminimize is removed
  file:
    path: /etc/update-motd.d/60-unminimize
    state: absent

- name: Ensure /etc/update-motd.d/10-help-text is removed
  file:
    path: /etc/update-motd.d/10-help-text
    state: absent

- name: Add infra ansible managed MOTD script
  copy:
    dest: /etc/update-motd.d/60-infra-ansible-managed
    content: |
      #!/bin/sh
      echo ""
      echo "🚀  This system is managed by Ansible! 🚀"
      echo ""
      echo "https://github.com/mtnstar/infra"
      echo ""
    owner: root
    group: root
    mode: "0755"

- name: install util-linux-extra for timezone setting
  apt:
    name: util-linux-extra
    state: present

- name: Set timezone
  ansible.builtin.timezone:
    name: "{{ timezone }}"

- name: Disable IPv6 via sysctl
  when: not (skip_ipv6_disable | default(false))
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    sysctl_set: true
    reload: true
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Ensure unattended-upgrades is installed
  apt:
    name: unattended-upgrades
    state: present
    update_cache: true

- name: Ensure automatic updates are enabled
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    owner: root
    group: root
    mode: "0644"

- name: Ensure unattended-upgrades service is enabled and running
  systemd:
    name: unattended-upgrades.service
    enabled: true
    state: started

- name: Force a reload of unattended-upgrades configuration
  command: dpkg-reconfigure -f noninteractive unattended-upgrades
  changed_when: false

- name: install iputils-ping, dnsutils, and net-tools
  apt:
    name:
      - iputils-ping
      - dnsutils
      - net-tools
    state: present
