---
driver:
  name: podman
platforms:
  - name: instance
    image: ghcr.io/mtnstar/infra-test-ubuntu:24.04
    pre_build_image: true
verifier:
  name: testinfra
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../.galaxy/roles:../../roles"
  inventory:
    hosts:
      all:
        hosts:
          instance:
            #task_list: ["1_install", "2_server-config"] 
            ansible_user: test-admin
            bootstrap_user: test-bootstrap
            timezone: "Europe/Zurich"
