---
driver:
  name: podman
platforms:
  - name: testhost-ubuntu-24.04
    image: ghcr.io/mtnstar/infra-test-ubuntu:24.04
    pre_build_image: true
verifier:
  name: testinfra
  options:
    sudo: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../.galaxy/roles:../../roles"
    ANSIBLE_VAULT_PASSWORD_FILE: "../.ansible_vault_pass.txt"
  inventory:
    links:
      group_vars: "../../inventories/test/group_vars/"
      host_vars: "../../inventories/test/host_vars/"
      hosts: "../../inventories/test/hosts"

