---
- name: Create WireGuard configuration directory
  ansible.builtin.file:
    path: /etc/wireguard
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: When WireGuard config exists, extract existing keys
  include_tasks: "process-server-keys.yml"

- name: Display public key
  ansible.builtin.debug:
    msg: "WireGuard Public Key: {{ wireguard_server_public_key }}"

- name: Deploy WireGuard interface configuration
  ansible.builtin.template:
    src: wg-interface.conf.j2
    dest: "/etc/wireguard/{{ wireguard_interface }}.conf"
    mode: '0600'
    owner: root
    group: root
