---
- name: Load common wireguard facts
  include_tasks: "facts.yml"

- name: Set local_user
  ansible.builtin.set_fact:
    local_user: "{{ lookup('env', 'USER') }}"

- name: Set local_wireguard_client_config_dir
  ansible.builtin.set_fact:
    local_wireguard_client_config_dir: "{{ local_wireguard_config_dir }}/clients"

- name: Make sure client config directory exists for given inventory
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ local_wireguard_client_config_dir }}"
    state: directory
    mode: "0700"
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
  changed_when: false

- name: Create client config files
  include_tasks: "create-client-config.yml"
  loop_control:
    loop_var: client
  loop: "{{ wireguard_client_peers }}"
