---
- name: Set local_user
  ansible.builtin.set_fact:
    local_user: "{{ lookup('env', 'USER') }}"

- name: Set local_tmp_bkp_config_dir
  set_fact:
    local_tmp_bkp_config_dir: "/home/{{ local_user }}/tmp/ansible"

- name: Set local_tmp_server_bkp_config_path
  set_fact:
    local_tmp_server_bkp_config_path: "{{ local_tmp_bkp_config_dir }}/wg0.conf"

- name: Make sure tmp config directory exists
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ local_tmp_bkp_config_dir }}"
    state: directory
    mode: "0700"
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
  changed_when: false

- name: Make sure wireguard_configs directory exists for given inventory
  delegate_to: localhost
  become: yes
  become_user: "{{ local_user }}"
  ansible.builtin.file:
    path: "{{ inventory_dir }}/wireguard_configs"
    state: directory
    mode: "0700"
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
  changed_when: false

- name: Fetch WireGuard config from remote host
  fetch:
    src: /etc/wireguard/wg0.conf
    dest: "{{ local_tmp_server_bkp_config_path }}"
    flat: yes
  changed_when: false

- name: Change ownership of fetched file
  delegate_to: localhost
  file:
    path: "{{ local_tmp_server_bkp_config_path }}"
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: "0600"
  run_once: true
  changed_when: false

- name: Encrypt server config for if it has changed
  delegate_to: localhost
  become: yes
  become_user: "{{ local_user }}"
  shell: |
    set -euo pipefail
    if [ -f "{{ inventory_dir }}/wireguard_configs/wg0.conf.vault" ]; then
      if ansible-vault view "{{ inventory_dir }}/wireguard_configs/wg0.conf.vault" | cmp -s - "{{ local_tmp_server_bkp_config_path }}"; then
        exit 0
      fi
    fi
    ansible-vault encrypt "{{ local_tmp_server_bkp_config_path }}" --output "{{ inventory_dir }}/wireguard_configs/wg0.conf.vault"
  args:
    executable: /bin/bash
  changed_when: false

- name: Remove the unencrypted fetched file
  delegate_to: localhost
  file:
    path: "{{ local_tmp_server_bkp_config_path }}"
    state: absent
  changed_when: false
